// <auto-generated />
using System;
using ITInventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITInventory.Data.Migrations
{
    [DbContext(typeof(ITInventoryDbContext))]
    [Migration("20260805082548_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITInventory.Data.Entities.Circuit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CircuitCapacity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CircuitType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Circuits", "dbo");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries", "dbo");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.DeviceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DeviceCategories", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sunucu"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ağ Cihazı"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Güvenlik"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ses/Görüntü"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Depolama"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Yazıcı"
                        },
                        new
                        {
                            Id = 7,
                            Name = "İstemci"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sanallaştırma"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Güç/Altyapı"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Diğer"
                        });
                });

            modelBuilder.Entity("ITInventory.Data.Entities.DeviceProfileCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProfileName")
                        .IsUnique();

                    b.ToTable("DeviceProfileCatalog", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 5,
                            ProfileName = "Veri Depolama (NAS)"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            ProfileName = "Güvenlik Kameraları (CCTV / NVR)"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ProfileName = "Sunucu / Appliance (Linux)"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            ProfileName = "IP Telefon (VoIP)"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            ProfileName = "Kablosuz Ağ (Access Point)"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            ProfileName = "Ağ Cihazı (SAN Switch)"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            ProfileName = "Veri Depolama (Storage)"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            ProfileName = "Veri Depolama (Storage Server)"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            ProfileName = "Veri Depolama (Storage / NAS)"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            ProfileName = "Endüstriyel Ağ Geçidi (IoT)"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            ProfileName = "Sunucu Yönetim Kartı (OOB / Console)"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 8,
                            ProfileName = "Sanallaştırma (Container Host)"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            ProfileName = "Yük Dengeleyici (Load Balancer)"
                        },
                        new
                        {
                            Id = 14,
                            ProfileName = "NULL"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            ProfileName = "Ağ Cihazı (Router)"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            ProfileName = "Yazıcı (Printer / Print Server)"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            ProfileName = "Bütünleşik Sistem (HCI)"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            ProfileName = "Sunucu Yönetim (Console Server / OOB)"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            ProfileName = "Ağ Servisleri (SD-WAN)"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 8,
                            ProfileName = "Sanallaştırma (Yönetim Sunucusu)"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 9,
                            ProfileName = "UPS / Güç Yönetimi"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            ProfileName = "Sunucu (Linux/SAP)"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            ProfileName = "Sunucu (Linux)"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            ProfileName = "Sunucu Yönetim (Console Server)"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            ProfileName = "Sunucu (Unix)"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            ProfileName = "Güvenlik / Ağ Cihazı"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            ProfileName = "Ağ Cihazı (Switch / Router)"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            ProfileName = "Güvenlik (Firewall)"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 4,
                            ProfileName = "IP Telefon / Santral"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            ProfileName = "Ağ Cihazı (Genel)"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            ProfileName = "Ağ Cihazı (Switch)"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 6,
                            ProfileName = "Yazıcı (Printer)"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 1,
                            ProfileName = "Sunucu Yönetim Kartı (OOB)"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 6,
                            ProfileName = "Yazıcı (Print Server)"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 1,
                            ProfileName = "Sunucu / Appliance (Linux/IoT)"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 8,
                            ProfileName = "Sanallaştırma (Hypervisor)"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 3,
                            ProfileName = "Güvenlik Kameraları (CCTV)"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 1,
                            ProfileName = "Sunucu (Windows)"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            ProfileName = "Medya Oynatıcı / Akıllı Ekran"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 2,
                            ProfileName = "Ağ Servisleri (DDI)"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 7,
                            ProfileName = "İstemci Bilgisayar (Workstation)"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 4,
                            ProfileName = "IP Telefon (Analog Gateway)"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 3,
                            ProfileName = "Güvenlik (Appliance)"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 7,
                            ProfileName = "İstemci Bilgisayar (Workstation / Medya)"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 1,
                            ProfileName = "Sunucu (Unix/Mainframe)"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 2,
                            ProfileName = "Ağ Cihazı (Switch / HCI)"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 3,
                            ProfileName = "Ağ Cihazı (Router / Firewall)"
                        });
                });

            modelBuilder.Entity("ITInventory.Data.Entities.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LicenseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SupportEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SupportStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VendorSupplier")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Licenses", "dbo");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.PhysicalDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplianceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Branch")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("DeviceProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndOfLifeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndOfSupportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LicenceInfo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MgmtIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SoftwareVersion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("SourceZiraatYdId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartOfSupportDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VendorSupplier")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CountryId");

                    b.HasIndex("DeviceProfileId");

                    b.ToTable("PhysicalDevices", "dbo");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplianceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Branch")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DeviceProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndOfLifeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndOfSupportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Model")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Port")
                        .HasColumnType("int");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("SourceZiraatYdId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartOfSupportDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VendorSupplier")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("DeviceProfileId");

                    b.ToTable("Servers", "dbo");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.YdRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("YDRoles", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ITInventory.Data.Entities.YdUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RepositoryName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("YDUsers", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ITInventory.Data.Entities.YdUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("YDUserRoles", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ITInventory.Data.Entities.ZiraatYd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceProfile")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DnsName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FirstSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("macAddress");

                    b.Property<string>("NetbiosName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("netbiosName");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("operatingSystem");

                    b.Property<int?>("PluginId")
                        .HasColumnType("int");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("ProfileSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Protocol")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RepositoryId")
                        .HasColumnType("int");

                    b.Property<string>("RepositoryName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("TenableFirstSeen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TenableLastSeen")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Ziraat_YD", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ITInventory.Data.Entities.Circuit", b =>
                {
                    b.HasOne("ITInventory.Data.Entities.Country", "Country")
                        .WithMany("Circuits")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.DeviceProfileCatalog", b =>
                {
                    b.HasOne("ITInventory.Data.Entities.DeviceCategory", "Category")
                        .WithMany("DeviceProfiles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.License", b =>
                {
                    b.HasOne("ITInventory.Data.Entities.Country", "Country")
                        .WithMany("Licenses")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.PhysicalDevice", b =>
                {
                    b.HasOne("ITInventory.Data.Entities.DeviceCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITInventory.Data.Entities.Country", "Country")
                        .WithMany("PhysicalDevices")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITInventory.Data.Entities.DeviceProfileCatalog", "DeviceProfile")
                        .WithMany()
                        .HasForeignKey("DeviceProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Country");

                    b.Navigation("DeviceProfile");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.Server", b =>
                {
                    b.HasOne("ITInventory.Data.Entities.Country", "Country")
                        .WithMany("Servers")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITInventory.Data.Entities.DeviceProfileCatalog", "DeviceProfile")
                        .WithMany()
                        .HasForeignKey("DeviceProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Country");

                    b.Navigation("DeviceProfile");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.YdUserRole", b =>
                {
                    b.HasOne("ITInventory.Data.Entities.YdRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITInventory.Data.Entities.YdUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.Country", b =>
                {
                    b.Navigation("Circuits");

                    b.Navigation("Licenses");

                    b.Navigation("PhysicalDevices");

                    b.Navigation("Servers");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.DeviceCategory", b =>
                {
                    b.Navigation("DeviceProfiles");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.YdRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.YdUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
