// <auto-generated />
using System;
using ITInventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITInventory.Data.Migrations
{
    [DbContext(typeof(ITInventoryDbContext))]
    [Migration("20260810072801_SplitServerIntoHostAndEndpoints")]
    partial class SplitServerIntoHostAndEndpoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ITInventory.Data.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationType")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsCloudApplication")
                        .HasColumnType("bit");

                    b.Property<bool>("IsExternallyExposed")
                        .HasColumnType("bit");

                    b.Property<int?>("LicenseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CountryId");

                    b.HasIndex("LicenseId");

                    b.ToTable("Applications", "dbo");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.Circuit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("CircuitCapacity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CircuitType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Circuits", "dbo");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("OriginCountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("OriginCountryId");

                    b.HasIndex("Name", "CountryId")
                        .IsUnique();

                    b.ToTable("Companies", "dbo");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.CompanyContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PersonName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyContacts", "dbo");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries", "dbo");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.DeviceCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DeviceCategories", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Server"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Network Device"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Security"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Audio/Video"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Storage"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Printer"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Client"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Virtualization"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Power/Infrastructure"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("ITInventory.Data.Entities.DeviceProfileCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProfileName")
                        .IsUnique();

                    b.ToTable("DeviceProfileCatalog", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 5,
                            DisplayName = "Data Storage (NAS)",
                            ProfileName = "Veri Depolama (NAS)"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            DisplayName = "Security Cameras (CCTV / NVR)",
                            ProfileName = "Güvenlik Kameraları (CCTV / NVR)"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DisplayName = "Server / Appliance (Linux)",
                            ProfileName = "Sunucu / Appliance (Linux)"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            DisplayName = "IP Phone (VoIP)",
                            ProfileName = "IP Telefon (VoIP)"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            DisplayName = "Wireless Network (Access Point)",
                            ProfileName = "Kablosuz Ağ (Access Point)"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            DisplayName = "Network Device (SAN Switch)",
                            ProfileName = "Ağ Cihazı (SAN Switch)"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 5,
                            DisplayName = "Data Storage (Storage)",
                            ProfileName = "Veri Depolama (Storage)"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            DisplayName = "Data Storage (Storage Server)",
                            ProfileName = "Veri Depolama (Storage Server)"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            DisplayName = "Data Storage (Storage / NAS)",
                            ProfileName = "Veri Depolama (Storage / NAS)"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            DisplayName = "Industrial Gateway (IoT)",
                            ProfileName = "Endüstriyel Ağ Geçidi (IoT)"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            DisplayName = "Server Management Card (OOB / Console)",
                            ProfileName = "Sunucu Yönetim Kartı (OOB / Console)"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 8,
                            DisplayName = "Virtualization (Container Host)",
                            ProfileName = "Sanallaştırma (Container Host)"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            DisplayName = "Load Balancer",
                            ProfileName = "Yük Dengeleyici (Load Balancer)"
                        },
                        new
                        {
                            Id = 14,
                            DisplayName = "Unmapped",
                            ProfileName = "NULL"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            DisplayName = "Network Device (Router)",
                            ProfileName = "Ağ Cihazı (Router)"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            DisplayName = "Printer (Printer / Print Server)",
                            ProfileName = "Yazıcı (Printer / Print Server)"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 1,
                            DisplayName = "Hyperconverged Infrastructure (HCI)",
                            ProfileName = "Bütünleşik Sistem (HCI)"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 1,
                            DisplayName = "Server Management (Console Server / OOB)",
                            ProfileName = "Sunucu Yönetim (Console Server / OOB)"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            DisplayName = "Network Services (SD-WAN)",
                            ProfileName = "Ağ Servisleri (SD-WAN)"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 8,
                            DisplayName = "Virtualization (Management Server)",
                            ProfileName = "Sanallaştırma (Yönetim Sunucusu)"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 9,
                            DisplayName = "UPS / Power Management",
                            ProfileName = "UPS / Güç Yönetimi"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            DisplayName = "Server (Linux/SAP)",
                            ProfileName = "Sunucu (Linux/SAP)"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            DisplayName = "Server (Linux)",
                            ProfileName = "Sunucu (Linux)"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 1,
                            DisplayName = "Server Management (Console Server)",
                            ProfileName = "Sunucu Yönetim (Console Server)"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            DisplayName = "Server (Unix)",
                            ProfileName = "Sunucu (Unix)"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 3,
                            DisplayName = "Security / Network Device",
                            ProfileName = "Güvenlik / Ağ Cihazı"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 2,
                            DisplayName = "Network Device (Switch / Router)",
                            ProfileName = "Ağ Cihazı (Switch / Router)"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 3,
                            DisplayName = "Security (Firewall)",
                            ProfileName = "Güvenlik (Firewall)"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 4,
                            DisplayName = "IP Phone / PBX",
                            ProfileName = "IP Telefon / Santral"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            DisplayName = "Network Device (General)",
                            ProfileName = "Ağ Cihazı (Genel)"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 2,
                            DisplayName = "Network Device (Switch)",
                            ProfileName = "Ağ Cihazı (Switch)"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 6,
                            DisplayName = "Printer",
                            ProfileName = "Yazıcı (Printer)"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 1,
                            DisplayName = "Server Management Card (OOB)",
                            ProfileName = "Sunucu Yönetim Kartı (OOB)"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 6,
                            DisplayName = "Printer (Print Server)",
                            ProfileName = "Yazıcı (Print Server)"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 1,
                            DisplayName = "Server / Appliance (Linux/IoT)",
                            ProfileName = "Sunucu / Appliance (Linux/IoT)"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 8,
                            DisplayName = "Virtualization (Hypervisor)",
                            ProfileName = "Sanallaştırma (Hypervisor)"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 3,
                            DisplayName = "Security Cameras (CCTV)",
                            ProfileName = "Güvenlik Kameraları (CCTV)"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 1,
                            DisplayName = "Server (Windows)",
                            ProfileName = "Sunucu (Windows)"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 4,
                            DisplayName = "Media Player / Smart Display",
                            ProfileName = "Medya Oynatıcı / Akıllı Ekran"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 2,
                            DisplayName = "Network Services (DDI)",
                            ProfileName = "Ağ Servisleri (DDI)"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 7,
                            DisplayName = "Client Computer (Workstation)",
                            ProfileName = "İstemci Bilgisayar (Workstation)"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 4,
                            DisplayName = "IP Phone (Analog Gateway)",
                            ProfileName = "IP Telefon (Analog Gateway)"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 3,
                            DisplayName = "Security (Appliance)",
                            ProfileName = "Güvenlik (Appliance)"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 7,
                            DisplayName = "Client Computer (Workstation / Media)",
                            ProfileName = "İstemci Bilgisayar (Workstation / Medya)"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 1,
                            DisplayName = "Server (Unix/Mainframe)",
                            ProfileName = "Sunucu (Unix/Mainframe)"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 2,
                            DisplayName = "Network Device (Switch / HCI)",
                            ProfileName = "Ağ Cihazı (Switch / HCI)"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 3,
                            DisplayName = "Network Device (Router / Firewall)",
                            ProfileName = "Ağ Cihazı (Router / Firewall)"
                        });
                });

            modelBuilder.Entity("ITInventory.Data.Entities.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SupportEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SupportStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VendorSupplier")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CountryId");

                    b.ToTable("Licenses", "dbo");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId", "Branch")
                        .IsUnique();

                    b.ToTable("Locations", "dbo");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.OriginCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OriginCountries", "dbo");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.PhysicalDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplianceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Branch")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("DeviceProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndOfLifeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndOfSupportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LicenceInfo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MgmtIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SoftwareVersion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("SourceZiraatYdId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartOfSupportDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VendorSupplier")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CountryId");

                    b.HasIndex("DeviceProfileId");

                    b.ToTable("PhysicalDevices", "dbo");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.Server", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplianceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Branch")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DeviceProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndOfLifeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndOfSupportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("HostPhysicalDeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Model")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SerialNo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("SourceZiraatYdId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartOfSupportDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VendorSupplier")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("DeviceProfileId");

                    b.HasIndex("HostPhysicalDeviceId");

                    b.ToTable("Servers", "dbo");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.ServerEndpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Port")
                        .HasColumnType("int");

                    b.Property<int>("ServerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ServerId");

                    b.ToTable("ServerEndpoints", "dbo");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.YdRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("YDRoles", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ITInventory.Data.Entities.YdUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RepositoryName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("YDUsers", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ITInventory.Data.Entities.YdUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("YDUserRoles", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ITInventory.Data.Entities.ZiraatYd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceProfile")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DnsName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FirstSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("macAddress");

                    b.Property<string>("NetbiosName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("netbiosName");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("operatingSystem");

                    b.Property<int?>("PluginId")
                        .HasColumnType("int");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<string>("ProfileSource")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Protocol")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RepositoryId")
                        .HasColumnType("int");

                    b.Property<string>("RepositoryName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("TenableFirstSeen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TenableLastSeen")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Ziraat_YD", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ITInventory.Data.Entities.Application", b =>
                {
                    b.HasOne("ITInventory.Data.Entities.Company", "Company")
                        .WithMany("Applications")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ITInventory.Data.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITInventory.Data.Entities.License", "License")
                        .WithMany()
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("Country");

                    b.Navigation("License");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.Circuit", b =>
                {
                    b.HasOne("ITInventory.Data.Entities.Country", "Country")
                        .WithMany("Circuits")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.Company", b =>
                {
                    b.HasOne("ITInventory.Data.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITInventory.Data.Entities.OriginCountry", "OriginCountry")
                        .WithMany("Companies")
                        .HasForeignKey("OriginCountryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Country");

                    b.Navigation("OriginCountry");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.CompanyContact", b =>
                {
                    b.HasOne("ITInventory.Data.Entities.Company", "Company")
                        .WithMany("Contacts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.DeviceProfileCatalog", b =>
                {
                    b.HasOne("ITInventory.Data.Entities.DeviceCategory", "Category")
                        .WithMany("DeviceProfiles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.License", b =>
                {
                    b.HasOne("ITInventory.Data.Entities.Company", "Company")
                        .WithMany("Licenses")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ITInventory.Data.Entities.Country", "Country")
                        .WithMany("Licenses")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.Location", b =>
                {
                    b.HasOne("ITInventory.Data.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.PhysicalDevice", b =>
                {
                    b.HasOne("ITInventory.Data.Entities.DeviceCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITInventory.Data.Entities.Country", "Country")
                        .WithMany("PhysicalDevices")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITInventory.Data.Entities.DeviceProfileCatalog", "DeviceProfile")
                        .WithMany()
                        .HasForeignKey("DeviceProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Country");

                    b.Navigation("DeviceProfile");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.Server", b =>
                {
                    b.HasOne("ITInventory.Data.Entities.Country", "Country")
                        .WithMany("Servers")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ITInventory.Data.Entities.DeviceProfileCatalog", "DeviceProfile")
                        .WithMany()
                        .HasForeignKey("DeviceProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ITInventory.Data.Entities.PhysicalDevice", "HostPhysicalDevice")
                        .WithMany()
                        .HasForeignKey("HostPhysicalDeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Country");

                    b.Navigation("DeviceProfile");

                    b.Navigation("HostPhysicalDevice");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.ServerEndpoint", b =>
                {
                    b.HasOne("ITInventory.Data.Entities.Application", "Application")
                        .WithMany("ServerEndpoints")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ITInventory.Data.Entities.Server", "Server")
                        .WithMany("Endpoints")
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.YdUserRole", b =>
                {
                    b.HasOne("ITInventory.Data.Entities.YdRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ITInventory.Data.Entities.YdUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.Application", b =>
                {
                    b.Navigation("ServerEndpoints");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.Company", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Contacts");

                    b.Navigation("Licenses");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.Country", b =>
                {
                    b.Navigation("Circuits");

                    b.Navigation("Licenses");

                    b.Navigation("PhysicalDevices");

                    b.Navigation("Servers");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.DeviceCategory", b =>
                {
                    b.Navigation("DeviceProfiles");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.OriginCountry", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.Server", b =>
                {
                    b.Navigation("Endpoints");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.YdRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ITInventory.Data.Entities.YdUser", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
