import { Question } from './types.ts';

export const QUESTIONS: Question[] = [
  // --- DÜNYA KUPASI TARİHİ ---
  { id: 'w1', text: 'Dünya Kupası tarihinde atılan ilk golün sahibi kimdir?', options: ['Lucien Laurent', 'Héctor Castro', 'Bert Patenaude', 'Guillermo Stábile'], correctAnswer: 'Lucien Laurent', category: 'Dünya Kupası' },
  { id: 'w2', text: '1950 Dünya Kupası\'nda Brezilya\'yı yıkan "Maracanazo" maçında Uruguay\'ın galibiyet golünü kim atmıştır?', options: ['Alcides Ghiggia', 'Obdulio Varela', 'Juan Alberto Schiaffino', 'Roque Máspoli'], correctAnswer: 'Alcides Ghiggia', category: 'Dünya Kupası' },
  { id: 'w3', text: 'Dünya Kupası tarihinde hem oyuncu hem de teknik direktör olarak şampiyonluk yaşayan ilk kişi kimdir?', options: ['Mario Zagallo', 'Franz Beckenbauer', 'Didier Deschamps', 'Vittorio Pozzo'], correctAnswer: 'Mario Zagallo', category: 'Dünya Kupası' },
  { id: 'w4', text: '1994 Dünya Kupası\'nda bir maçta 5 gol atarak rekor kıran Rus futbolcu kimdir?', options: ['Oleg Salenko', 'Hristo Stoichkov', 'Romario', 'Roberto Baggio'], correctAnswer: 'Oleg Salenko', category: 'Dünya Kupası' },
  { id: 'w5', text: 'Dünya Kupası tarihinde en çok gol atan oyuncu kimdir?', options: ['Miroslav Klose', 'Ronaldo Nazario', 'Gerd Müller', 'Pele'], correctAnswer: 'Miroslav Klose', category: 'Dünya Kupası' },
  { id: 'w6', text: 'Hangi ülke Dünya Kupası\'nı kendi evinde kazanmamıştır?', options: ['Brezilya', 'İngiltere', 'Fransa', 'Almanya'], correctAnswer: 'Brezilya', category: 'Dünya Kupası' },
  { id: 'w7', text: '2010 Dünya Kupası finalinde İspanya\'ya şampiyonluğu getiren golü kim atmıştır?', options: ['Andres Iniesta', 'Xavi', 'David Villa', 'Fernando Torres'], correctAnswer: 'Andres Iniesta', category: 'Dünya Kupası' },
  { id: 'w8', text: 'Dünya Kupası tarihinde kırmızı kart gören ilk futbolcu kimdir?', options: ['Carlos Caszely', 'Zinedine Zidane', 'Antonio Rattin', 'Garrincha'], correctAnswer: 'Carlos Caszely', category: 'Dünya Kupası' },
  { id: 'w9', text: '1930 Dünya Kupası finalinde kullanılan topun adı nedir?', options: ['Tiento', 'Allen', 'Federale', 'Superball'], correctAnswer: 'Tiento', category: 'Dünya Kupası' },
  { id: 'w10', text: 'Dünya Kupası tarihinde en genç gol atan oyuncu kimdir?', options: ['Pele', 'Lionel Messi', 'Kylian Mbappe', 'Gavi'], correctAnswer: 'Pele', category: 'Dünya Kupası' },
  { id: 'w11', text: '1966 Dünya Kupası finalinde hat-trick yapan tek oyuncu kimdir?', options: ['Geoff Hurst', 'Bobby Charlton', 'Eusebio', 'Uwe Seeler'], correctAnswer: 'Geoff Hurst', category: 'Dünya Kupası' },
  { id: 'w12', text: 'Dünya Kupası tarihinde üst üste iki kez şampiyon olan ülkeler hangileridir?', options: ['İtalya ve Brezilya', 'Brezilya ve Almanya', 'Arjantin ve Fransa', 'Uruguay ve İtalya'], correctAnswer: 'İtalya ve Brezilya', category: 'Dünya Kupası' },
  { id: 'w13', text: '2002 Dünya Kupası\'nın en golcü oyuncusu (Altın Ayakkabı) kimdir?', options: ['Ronaldo Nazario', 'Miroslav Klose', 'Rivaldo', 'Hasan Şaş'], correctAnswer: 'Ronaldo Nazario', category: 'Dünya Kupası' },
  { id: 'w14', text: 'Dünya Kupası tarihinde bir turnuvada en çok gol atan oyuncu (13 gol) kimdir?', options: ['Just Fontaine', 'Gerd Müller', 'Sandor Kocsis', 'Ademir'], correctAnswer: 'Just Fontaine', category: 'Dünya Kupası' },
  { id: 'w15', text: 'Hangi ülke Dünya Kupası tarihinde en çok final kaybetmiştir?', options: ['Almanya', 'Arjantin', 'Hollanda', 'Brezilya'], correctAnswer: 'Almanya', category: 'Dünya Kupası' },
  { id: 'w16', text: '1986 Dünya Kupası\'nda Arjantin-İngiltere maçında "Tanrı\'nın Eli" golünü kim atmıştır?', options: ['Diego Maradona', 'Jorge Valdano', 'Oscar Ruggeri', 'Burruchaga'], correctAnswer: 'Diego Maradona', category: 'Dünya Kupası' },
  { id: 'w17', text: 'Dünya Kupası tarihinde en çok maça çıkan oyuncu kimdir?', options: ['Lionel Messi', 'Lothar Matthäus', 'Miroslav Klose', 'Paolo Maldini'], correctAnswer: 'Lionel Messi', category: 'Dünya Kupası' },
  { id: 'w18', text: '2006 Dünya Kupası finalinde Zinedine Zidane kime kafa atmıştır?', options: ['Marco Materazzi', 'Fabio Cannavaro', 'Gennaro Gattuso', 'Gianluigi Buffon'], correctAnswer: 'Marco Materazzi', category: 'Dünya Kupası' },
  { id: 'w19', text: 'Dünya Kupası tarihinde bir maçta en çok gol atan oyuncu (5 gol) kimdir?', options: ['Oleg Salenko', 'Just Fontaine', 'Eusebio', 'Emilio Butragueño'], correctAnswer: 'Oleg Salenko', category: 'Dünya Kupası' },
  { id: 'w20', text: 'Hangi ülke Dünya Kupası\'nı 5 kez kazanarak bu alanda liderdir?', options: ['Brezilya', 'Almanya', 'İtalya', 'Arjantin'], correctAnswer: 'Brezilya', category: 'Dünya Kupası' },

  // --- ŞAMPİYONLAR LİGİ / AVRUPA ---
  { id: 'cl1', text: 'Şampiyonlar Ligi kupasını üst üste 5 kez kazanan tek takım hangisidir?', options: ['Real Madrid', 'AC Milan', 'Bayern Münih', 'Liverpool'], correctAnswer: 'Real Madrid', category: 'Şampiyonlar Ligi' },
  { id: 'cl2', text: '2005 İstanbul finalinde Milan karşısında 3-0\'dan dönüp kupayı kazanan Liverpool\'un kaptanı kimdir?', options: ['Steven Gerrard', 'Jamie Carragher', 'Xabi Alonso', 'Sami Hyypia'], correctAnswer: 'Steven Gerrard', category: 'Şampiyonlar Ligi' },
  { id: 'cl3', text: 'Şampiyonlar Ligi tarihinde bir sezonda en çok gol atan oyuncu kimdir?', options: ['Cristiano Ronaldo', 'Lionel Messi', 'Robert Lewandowski', 'Erling Haaland'], correctAnswer: 'Cristiano Ronaldo', category: 'Şampiyonlar Ligi' },
  { id: 'cl4', text: 'Hangi futbolcu 3 farklı kulüple Şampiyonlar Ligi şampiyonluğu yaşamıştır?', options: ['Clarence Seedorf', 'Cristiano Ronaldo', 'Samuel Eto\'o', 'Zlatan Ibrahimovic'], correctAnswer: 'Clarence Seedorf', category: 'Şampiyonlar Ligi' },
  { id: 'cl5', text: '2004 yılında Porto ile Şampiyonlar Ligi\'ni kazanan teknik direktör kimdir?', options: ['Jose Mourinho', 'Pep Guardiola', 'Carlo Ancelotti', 'Sir Alex Ferguson'], correctAnswer: 'Jose Mourinho', category: 'Şampiyonlar Ligi' },
  { id: 'cl6', text: 'Şampiyonlar Ligi tarihinin en hızlı golünü (10.12 saniye) kim atmıştır?', options: ['Roy Makaay', 'Jonas', 'Gilberto Silva', 'Alessandro Del Piero'], correctAnswer: 'Roy Makaay', category: 'Şampiyonlar Ligi' },
  { id: 'cl7', text: 'Hangi şehir Şampiyonlar Ligi finaline en çok ev sahipliği yapmıştır?', options: ['Londra', 'Paris', 'Münih', 'Madrid'], correctAnswer: 'Londra', category: 'Şampiyonlar Ligi' },
  { id: 'cl8', text: '2012 Şampiyonlar Ligi finalinde Chelsea, Bayern Münih\'i kimin penaltısıyla yenmiştir?', options: ['Didier Drogba', 'Frank Lampard', 'Ashley Cole', 'Petr Cech'], correctAnswer: 'Didier Drogba', category: 'Şampiyonlar Ligi' },
  { id: 'cl9', text: 'Şampiyonlar Ligi tarihinde en çok maça çıkan oyuncu kimdir?', options: ['Cristiano Ronaldo', 'Iker Casillas', 'Lionel Messi', 'Xavi'], correctAnswer: 'Cristiano Ronaldo', category: 'Şampiyonlar Ligi' },
  { id: 'cl10', text: 'Hangi takım Şampiyonlar Ligi\'nde bir sezondaki tüm maçlarını kazanarak şampiyon olmuştur?', options: ['Bayern Münih (2020)', 'Real Madrid (2017)', 'Barcelona (2009)', 'Manchester City (2023)'], correctAnswer: 'Bayern Münih (2020)', category: 'Şampiyonlar Ligi' },
  { id: 'cl11', text: 'Şampiyonlar Ligi tarihinde bir maçta 5 gol atan ilk oyuncu kimdir?', options: ['Lionel Messi', 'Luiz Adriano', 'Erling Haaland', 'Cristiano Ronaldo'], correctAnswer: 'Lionel Messi', category: 'Şampiyonlar Ligi' },
  { id: 'cl12', text: 'Zinedine Zidane\'ın 2002 finalinde Bayer Leverkusen\'e attığı efsanevi vole golünde asisti kim yapmıştır?', options: ['Roberto Carlos', 'Luis Figo', 'Raul', 'Claude Makelele'], correctAnswer: 'Roberto Carlos', category: 'Şampiyonlar Ligi' },
  { id: 'cl13', text: 'Hangi futbolcu Şampiyonlar Ligi tarihinde hem oyuncu hem teknik direktör olarak kupayı kazanmıştır?', options: ['Zinedine Zidane', 'Pep Guardiola', 'Carlo Ancelotti', 'Hepsi'], correctAnswer: 'Hepsi', category: 'Şampiyonlar Ligi' },
  { id: 'cl14', text: 'Şampiyonlar Ligi tarihinin en çok gol atan takımı hangisidir?', options: ['Real Madrid', 'Bayern Münih', 'Barcelona', 'Manchester United'], correctAnswer: 'Real Madrid', category: 'Şampiyonlar Ligi' },
  { id: 'cl15', text: '2019 Şampiyonlar Ligi finalinde Tottenham\'ı yenerek kupayı kazanan takım hangisidir?', options: ['Liverpool', 'Manchester City', 'Chelsea', 'Real Madrid'], correctAnswer: 'Liverpool', category: 'Şampiyonlar Ligi' },

  // --- TÜRKİYE FUTBOL TARİHİ ---
  { id: 'tr1', text: 'Türkiye Milli Takımı\'nın tarihindeki ilk golünü kim atmıştır?', options: ['Zeki Rıza Sporel', 'Lefter Küçükandonyadis', 'Metin Oktay', 'Gündüz Kılıç'], correctAnswer: 'Zeki Rıza Sporel', category: 'Türkiye' },
  { id: 'tr2', text: 'Süper Lig tarihinde bir sezonda en çok gol atan futbolcu kimdir?', options: ['Tanju Çolak', 'Metin Oktay', 'Hakan Şükür', 'Enner Valencia'], correctAnswer: 'Tanju Çolak', category: 'Türkiye' },
  { id: 'tr3', text: 'Galatasaray 2000 UEFA Kupası finalinde Arsenal\'i penaltılarda yenerken son penaltıyı kim atmıştır?', options: ['Gheorghe Popescu', 'Hakan Şükür', 'Ümit Davala', 'Ergün Penbe'], correctAnswer: 'Gheorghe Popescu', category: 'Türkiye' },
  { id: 'tr4', text: 'Türkiye Süper Lig tarihinde "Dört Büyükler" dışındaki ilk şampiyon hangisidir?', options: ['Trabzonspor', 'Bursaspor', 'Başakşehir', 'Eskişehirspor'], correctAnswer: 'Trabzonspor', category: 'Türkiye' },
  { id: 'tr5', text: 'Beşiktaş\'ın 1991-92 sezonundaki namağlup şampiyonluğunda teknik direktör kimdir?', options: ['Gordon Milne', 'Christoph Daum', 'Mircea Lucescu', 'Şenol Güneş'], correctAnswer: 'Gordon Milne', category: 'Türkiye' },
  { id: 'tr6', text: 'Fenerbahçe\'nin 2007-08 Şampiyonlar Ligi çeyrek finalindeki teknik direktörü kimdir?', options: ['Zico', 'Christoph Daum', 'Luis Aragones', 'Aykut Kocaman'], correctAnswer: 'Zico', category: 'Türkiye' },
  { id: 'tr7', text: 'Süper Lig tarihinde en çok şampiyonluk yaşayan teknik direktör kimdir?', options: ['Fatih Terim', 'Mustafa Denizli', 'Şenol Güneş', 'Ahmet Suat Özyazıcı'], correctAnswer: 'Fatih Terim', category: 'Türkiye' },
  { id: 'tr8', text: 'EURO 2008 çeyrek finalinde Hırvatistan\'a 120+2\'de gol atan oyuncumuz kimdir?', options: ['Semih Şentürk', 'Nihat Kahveci', 'Arda Turan', 'Tuncay Şanlı'], correctAnswer: 'Semih Şentürk', category: 'Türkiye' },
  { id: 'tr9', text: 'Türkiye Milli Takımı, 2002 Dünya Kupası üçüncülük maçında kimi yenmiştir?', options: ['Güney Kore', 'Senegal', 'Japonya', 'Brezilya'], correctAnswer: 'Güney Kore', category: 'Türkiye' },
  { id: 'tr10', text: 'Süper Lig tarihinde en çok gol atan yabancı futbolcu kimdir?', options: ['Alex de Souza', 'Bafetimbi Gomis', 'Shota Arveladze', 'Mauro Icardi'], correctAnswer: 'Alex de Souza', category: 'Türkiye' },
  { id: 'tr11', text: 'Fenerbahçe\'nin efsanevi futbolcusu Lefter Küçükandonyadis\'in lakabı nedir?', options: ['Ordinaryüs', 'Taçsız Kral', 'Sinyor', 'Altın Kafa'], correctAnswer: 'Ordinaryüs', category: 'Türkiye' },
  { id: 'tr12', text: 'Beşiktaş\'ın "Baba" lakaplı efsane başkanı kimdir?', options: ['Süleyman Seba', 'Hakkı Yeten', 'Şeref Bey', 'Yıldırım Demirören'], correctAnswer: 'Süleyman Seba', category: 'Türkiye' },
  { id: 'tr13', text: 'Galatasaray\'ın "Taçsız Kral" lakaplı efsane golcüsü kimdir?', options: ['Metin Oktay', 'Tanju Çolak', 'Hakan Şükür', 'Necati Ateş'], correctAnswer: 'Metin Oktay', category: 'Türkiye' },
  { id: 'tr14', text: 'Türkiye Milli Takımı\'nın EURO 2008\'deki teknik direktörü kimdir?', options: ['Fatih Terim', 'Şenol Güneş', 'Mustafa Denizli', 'Ersun Yanal'], correctAnswer: 'Fatih Terim', category: 'Türkiye' },
  { id: 'tr15', text: 'Süper Lig tarihinde 100 gol barajını geçen ilk futbolcu kimdir?', options: ['Metin Oktay', 'Lefter Küçükandonyadis', 'Hakan Şükür', 'Tanju Çolak'], correctAnswer: 'Metin Oktay', category: 'Türkiye' },

  // --- EFSANELER VE REKORLAR ---
  { id: 'leg1', text: 'Hangi futbolcu profesyonel kariyeri boyunca hiç sarı kart görmemiştir?', options: ['Gary Lineker', 'Bobby Charlton', 'Stanley Matthews', 'Hepsi'], correctAnswer: 'Hepsi', category: 'Efsaneler' },
  { id: 'leg2', text: 'Lev Yashin kariyeri boyunca yaklaşık kaç penaltı kurtarmıştır?', options: ['150', '50', '100', '200'], correctAnswer: '150', category: 'Efsaneler' },
  { id: 'leg3', text: 'Ballon d\'Or ödülünü kazanan tek kaleci kimdir?', options: ['Lev Yashin', 'Gianluigi Buffon', 'Manuel Neuer', 'Iker Casillas'], correctAnswer: 'Lev Yashin', category: 'Efsaneler' },
  { id: 'leg4', text: 'Zinedine Zidane kariyerindeki son maçında kime kafa atmıştır?', options: ['Marco Materazzi', 'Fabio Cannavaro', 'Gennaro Gattuso', 'Alessandro Del Piero'], correctAnswer: 'Marco Materazzi', category: 'Efsaneler' },
  { id: 'leg5', text: 'Lionel Messi, 2012 takvim yılında toplam kaç resmi gol atmıştır?', options: ['91', '85', '88', '94'], correctAnswer: '91', category: 'Efsaneler' },
  { id: 'leg6', text: 'Cristiano Ronaldo, Real Madrid formasıyla çıktığı maç sayısından (438) daha fazla gol mü atmıştır?', options: ['Evet (450 gol)', 'Hayır (420 gol)', 'Eşit (438 gol)', 'Hayır (380 gol)'], correctAnswer: 'Evet (450 gol)', category: 'Efsaneler' },
  { id: 'leg7', text: 'Hangi futbolcu "Dörtnala Binbaşı" lakabıyla tanınır?', options: ['Ferenc Puskas', 'Alfredo Di Stefano', 'Johan Cruyff', 'Franz Beckenbauer'], correctAnswer: 'Ferenc Puskas', category: 'Efsaneler' },
  { id: 'leg8', text: 'Johan Cruyff ile özdeşleşen oyun felsefesi hangisidir?', options: ['Total Futbol', 'Tiki-Taka', 'Catenaccio', 'Gegenpressing'], correctAnswer: 'Total Futbol', category: 'Efsaneler' },
  { id: 'leg9', text: 'Pele kariyeri boyunca kaç kez Dünya Kupası kazanmıştır?', options: ['3', '2', '4', '1'], correctAnswer: '3', category: 'Efsaneler' },
  { id: 'leg10', text: 'Diego Maradona\'nın "Yüzyılın Golü"nü attığı maç hangi ülkeye karşıydı?', options: ['İngiltere', 'Almanya', 'Brezilya', 'İtalya'], correctAnswer: 'İngiltere', category: 'Efsaneler' },
  { id: 'leg11', text: 'Hangi futbolcu "Siyah İnci" lakabıyla tanınır?', options: ['Pele', 'Eusebio', 'Larbi Benbarek', 'Arthur Friedenreich'], correctAnswer: 'Pele', category: 'Efsaneler' },
  { id: 'leg12', text: 'Franz Beckenbauer\'in lakabı nedir?', options: ['Der Kaiser (İmparator)', 'Der Bomber', 'Panzer', 'Kaptan'], correctAnswer: 'Der Kaiser (İmparator)', category: 'Efsaneler' },
  { id: 'leg13', text: 'Hangi futbolcu kariyeri boyunca en çok Ballon d\'Or kazanmıştır?', options: ['Lionel Messi', 'Cristiano Ronaldo', 'Michel Platini', 'Johan Cruyff'], correctAnswer: 'Lionel Messi', category: 'Efsaneler' },
  { id: 'leg14', text: 'Gerd Müller\'in lakabı nedir?', options: ['Der Bomber', 'Panzer', 'Uçan Alman', 'Gol Makinesi'], correctAnswer: 'Der Bomber', category: 'Efsaneler' },
  { id: 'leg15', text: 'Eusebio hangi ülkenin efsanevi futbolcusudur?', options: ['Portekiz', 'Brezilya', 'Angola', 'Mozambik'], correctAnswer: 'Portekiz', category: 'Efsaneler' },

  // --- MODERN FUTBOL (2020-2025) ---
  { id: 'mod1', text: '2024 Ballon d\'Or ödülünü kazanan futbolcu kimdir?', options: ['Rodri', 'Vinicius Jr', 'Jude Bellingham', 'Erling Haaland'], correctAnswer: 'Rodri', category: 'Modern' },
  { id: 'mod2', text: 'Bayer Leverkusen, 2023-24 sezonunda Bundesliga\'yı kaç mağlubiyetle tamamlamıştır?', options: ['0', '1', '2', '3'], correctAnswer: '0', category: 'Modern' },
  { id: 'mod3', text: 'Erling Haaland, Premier Lig\'deki ilk sezonunda kaç gol atarak rekor kırmıştır?', options: ['36', '32', '34', '38'], correctAnswer: '36', category: 'Modern' },
  { id: 'mod4', text: 'EURO 2024 finalinde İspanya hangi ülkeyi yenerek şampiyon olmuştur?', options: ['İngiltere', 'Fransa', 'Hollanda', 'Almanya'], correctAnswer: 'İngiltere', category: 'Modern' },
  { id: 'mod5', text: 'Arda Güler, Real Madrid formasıyla ilk golünü hangi takıma atmıştır?', options: ['Celta Vigo', 'Getafe', 'Granada', 'Alaves'], correctAnswer: 'Celta Vigo', category: 'Modern' },
  { id: 'mod6', text: '2022 Dünya Kupası finalinde hat-trick yapmasına rağmen kaybeden oyuncu kimdir?', options: ['Kylian Mbappe', 'Lionel Messi', 'Angel Di Maria', 'Julian Alvarez'], correctAnswer: 'Kylian Mbappe', category: 'Modern' },
  { id: 'mod7', text: 'Harry Kane, 2023 yazında hangi takıma transfer olmuştur?', options: ['Bayern Münih', 'Real Madrid', 'Manchester City', 'PSG'], correctAnswer: 'Bayern Münih', category: 'Modern' },
  { id: 'mod8', text: 'Hangi teknik direktör 2023\'te Manchester City ile "Treble" (3 kupa) yapmıştır?', options: ['Pep Guardiola', 'Thomas Tuchel', 'Erik ten Hag', 'Mikel Arteta'], correctAnswer: 'Pep Guardiola', category: 'Modern' },
  { id: 'mod9', text: '2024 Avrupa Şampiyonası\'nın (EURO 2024) en iyi genç oyuncusu kim seçilmiştir?', options: ['Lamine Yamal', 'Arda Güler', 'Kobbie Mainoo', 'Jude Bellingham'], correctAnswer: 'Lamine Yamal', category: 'Modern' },
  { id: 'mod10', text: 'Lionel Messi, 8. Ballon d\'Or ödülünü hangi yıl kazanmıştır?', options: ['2023', '2022', '2021', '2024'], correctAnswer: '2023', category: 'Modern' },
  { id: 'mod11', text: '2022 Dünya Kupası finalinde Arjantin kalecisi Emiliano Martinez, son dakikada hangi Fransız oyuncunun şutunu kurtarmıştır?', options: ['Kolo Muani', 'Kingsley Coman', 'Marcus Thuram', 'Olivier Giroud'], correctAnswer: 'Kolo Muani', category: 'Modern' },
  { id: 'mod12', text: 'Hangi futbolcu 2023 yılında Suudi Arabistan ligine transfer olarak büyük bir akım başlatmıştır?', options: ['Cristiano Ronaldo', 'Neymar', 'Karim Benzema', 'Sadio Mane'], correctAnswer: 'Cristiano Ronaldo', category: 'Modern' },
  { id: 'mod13', text: '2023 Şampiyonlar Ligi finalinde galibiyet golünü kim atmıştır?', options: ['Rodri', 'Erling Haaland', 'Kevin De Bruyne', 'Bernardo Silva'], correctAnswer: 'Rodri', category: 'Modern' },
  { id: 'mod14', text: 'Jude Bellingham 2023 yazında hangi takımdan Real Madrid\'e transfer olmuştur?', options: ['Borussia Dortmund', 'Birmingham City', 'Liverpool', 'Manchester City'], correctAnswer: 'Borussia Dortmund', category: 'Modern' },
  { id: 'mod15', text: 'EURO 2024 finalinde İspanya\'nın galibiyet golünü (2-1) kim atmıştır?', options: ['Mikel Oyarzabal', 'Nico Williams', 'Lamine Yamal', 'Dani Olmo'], correctAnswer: 'Mikel Oyarzabal', category: 'Modern' },

  // --- LİGLER VE KULÜPLER ---
  { id: 'l1', text: 'İngiltere Premier Lig tarihinde en çok gol atan oyuncu kimdir?', options: ['Alan Shearer', 'Harry Kane', 'Wayne Rooney', 'Sergio Agüero'], correctAnswer: 'Alan Shearer', category: 'Ligler' },
  { id: 'l2', text: 'Arsenal\'in 2003-04 sezonundaki namağlup şampiyonluk serisi kaç maç sürmüştür?', options: ['49', '38', '42', '52'], correctAnswer: '49', category: 'Ligler' },
  { id: 'l3', text: 'İtalya Serie A tarihinde en çok şampiyon olan takım hangisidir?', options: ['Juventus', 'Inter', 'Milan', 'Roma'], correctAnswer: 'Juventus', category: 'Ligler' },
  { id: 'l4', text: 'Almanya Bundesliga\'da üst üste 11 kez şampiyon olan takım hangisidir?', options: ['Bayern Münih', 'Borussia Dortmund', 'Bayer Leverkusen', 'RB Leipzig'], correctAnswer: 'Bayern Münih', category: 'Ligler' },
  { id: 'l5', text: 'Fransa Ligue 1 tarihinde en çok şampiyonluk yaşayan kulüp hangisidir?', options: ['PSG', 'Saint-Etienne', 'Marsilya', 'Lyon'], correctAnswer: 'PSG', category: 'Ligler' },
  { id: 'l6', text: 'Lionel Messi, Barcelona formasıyla toplam kaç resmi gol atmıştır?', options: ['672', '650', '700', '630'], correctAnswer: '672', category: 'Ligler' },
  { id: 'l7', text: 'Hangi futbolcu hem Real Madrid hem de Barcelona forması giymiştir?', options: ['Luis Figo', 'Ronaldo Nazario', 'Luis Enrique', 'Hepsi'], correctAnswer: 'Hepsi', category: 'Ligler' },
  { id: 'l8', text: 'Manchester City\'nin 2012\'deki mucizevi şampiyonluk golünü atan oyuncu kimdir?', options: ['Sergio Agüero', 'Edin Dzeko', 'David Silva', 'Yaya Toure'], correctAnswer: 'Sergio Agüero', category: 'Ligler' },
  { id: 'l9', text: 'Celtic ve Rangers rekabetine ne ad verilir?', options: ['Old Firm', 'El Clasico', 'Merseyside Derby', 'North London Derby'], correctAnswer: 'Old Firm', category: 'Ligler' },
  { id: 'l10', text: 'Hangi stadyum "Düşler Tiyatrosu" (Theatre of Dreams) olarak bilinir?', options: ['Old Trafford', 'Anfield', 'Wembley', 'Stamford Bridge'], correctAnswer: 'Old Trafford', category: 'Ligler' },

  // --- KARIŞIK / ZOR ---
  { id: 'hard1', text: 'Hangi futbolcu hem 20. yüzyılda hem de 21. yüzyılda Dünya Kupası finalinde gol atmıştır?', options: ['Zinedine Zidane', 'Pele', 'Ronaldo Nazario', 'Lionel Messi'], correctAnswer: 'Zinedine Zidane', category: 'Zor' },
  { id: 'hard2', text: 'Dünya Kupası tarihinde hiç gol yemeden elenen tek takım hangisidir?', options: ['İsviçre (2006)', 'Angola (2006)', 'Güney Kore (2002)', 'Yunanistan (2004)'], correctAnswer: 'İsviçre (2006)', category: 'Zor' },
  { id: 'hard3', text: 'Kariyeri boyunca en çok resmi kırmızı kart görme rekoru (46 kart) kime aittir?', options: ['Gerardo Bedoya', 'Sergio Ramos', 'Paolo Montero', 'Cyril Rool'], correctAnswer: 'Gerardo Bedoya', category: 'Zor' },
  { id: 'hard4', text: 'Nottingham Forest hangi yıllarda üst üste iki kez Avrupa Kupası kazanmıştır?', options: ['1979-1980', '1977-1978', '1981-1982', '1975-1976'], correctAnswer: '1979-1980', category: 'Zor' },
  { id: 'hard5', text: 'Resmi bir maçta en çok gol atan oyuncu rekoru (13 gol) kime aittir?', options: ['Archie Thompson', 'Stephan Stannis', 'John Petrie', 'Cosmo Damião'], correctAnswer: 'Archie Thompson', category: 'Zor' },
  { id: 'hard6', text: 'Hangi kaleci bir maçta hat-trick yapma başarısı göstermiştir?', options: ['Jose Luis Chilavert', 'Rogerio Ceni', 'Jorge Campos', 'Rene Higuita'], correctAnswer: 'Jose Luis Chilavert', category: 'Zor' },
  { id: 'hard7', text: 'Dünya Kupası kazanan en genç teknik direktör kimdir?', options: ['Alberto Suppici', 'Mario Zagallo', 'Lionel Scaloni', 'Cesar Luis Menotti'], correctAnswer: 'Alberto Suppici', category: 'Zor' },
  { id: 'hard8', text: '1962 Dünya Kupası\'ndaki "Santiago Savaşı" hangi iki takım arasındadır?', options: ['Şili - İtalya', 'Brezilya - Arjantin', 'Almanya - Macaristan', 'İngiltere - Arjantin'], correctAnswer: 'Şili - İtalya', category: 'Zor' },
  { id: 'hard9', text: 'Hangi futbolcu kariyeri boyunca 5 farklı Dünya Kupası\'nda gol atmıştır?', options: ['Cristiano Ronaldo', 'Lionel Messi', 'Miroslav Klose', 'Pele'], correctAnswer: 'Cristiano Ronaldo', category: 'Zor' },
  { id: 'hard10', text: '1954 Dünya Kupası finalindeki "Bern Mucizesi"nde Batı Almanya kimi yenmiştir?', options: ['Macaristan', 'Brezilya', 'Avusturya', 'Uruguay'], correctAnswer: 'Macaristan', category: 'Zor' },
  { id: 'hard11', text: 'Hangi futbolcu profesyonel kariyeri boyunca 1000\'den fazla resmi maça çıkmıştır?', options: ['Rogerio Ceni', 'Peter Shilton', 'Cristiano Ronaldo', 'Hepsi'], correctAnswer: 'Hepsi', category: 'Zor' },
  { id: 'hard12', text: 'Şampiyonlar Ligi tarihinde bir maçta en çok gol atan takım (8 gol) hangisidir?', options: ['Borussia Dortmund', 'Bayern Münih', 'Real Madrid', 'Monaco'], correctAnswer: 'Borussia Dortmund', category: 'Zor' },
  { id: 'hard13', text: 'Hangi futbolcu "Altın Ayakkabı" ödülünü 3 farklı ligde (Portekiz, İngiltere, İspanya) kazanmıştır?', options: ['Cristiano Ronaldo', 'Luis Suarez', 'Mario Jardel', 'Diego Forlan'], correctAnswer: 'Cristiano Ronaldo', category: 'Zor' },
  { id: 'hard14', text: 'Dünya Kupası tarihinde atılan en hızlı gol (11. saniye) kime aittir?', options: ['Hakan Şükür', 'Vaclav Masek', 'Bryan Robson', 'Bernard Lacombe'], correctAnswer: 'Hakan Şükür', category: 'Zor' },
  { id: 'hard15', text: 'Hangi ülke Dünya Kupası tarihinde en çok kırmızı kart görmüştür?', options: ['Brezilya', 'Arjantin', 'Uruguay', 'İtalya'], correctAnswer: 'Brezilya', category: 'Zor' },

  // --- EKSTRA SORULAR ---
  { id: 'e1', text: 'Zlatan Ibrahimovic kariyerinde hangi ligde oynamamıştır?', options: ['Bundesliga', 'Premier Lig', 'La Liga', 'Ligue 1'], correctAnswer: 'Bundesliga', category: 'Oyuncular' },
  { id: 'e2', text: 'Hangi ülke hem erkeklerde hem kadınlarda Dünya Kupası kazanmıştır?', options: ['Almanya', 'Brezilya', 'ABD', 'Fransa'], correctAnswer: 'Almanya', category: 'Dünya Kupası' },
  { id: 'e3', text: 'Ballon d\'Or kazanan ilk Afrikalı futbolcu kimdir?', options: ['George Weah', 'Samuel Eto\'o', 'Didier Drogba', 'Mohamed Salah'], correctAnswer: 'George Weah', category: 'Ödüller' },
  { id: 'e4', text: 'Hangi futbolcu "Siyah İnci" lakabıyla tanınır?', options: ['Pele', 'Eusebio', 'Larbi Benbarek', 'Arthur Friedenreich'], correctAnswer: 'Pele', category: 'Efsaneler' },
  { id: 'e5', text: '2004 Avrupa Şampiyonası\'nı (EURO 2004) kazanan ülke hangisidir?', options: ['Yunanistan', 'Portekiz', 'Çek Cumhuriyeti', 'Hollanda'], correctAnswer: 'Yunanistan', category: 'EURO' },
  { id: 'e6', text: 'Hangi teknik direktör "The Special One" lakabıyla bilinir?', options: ['Jose Mourinho', 'Pep Guardiola', 'Arsene Wenger', 'Jurgen Klopp'], correctAnswer: 'Jose Mourinho', category: 'Teknik Direktörler' },
  { id: 'e7', text: 'Kylian Mbappe 2024 yılında hangi takıma transfer olmuştur?', options: ['Real Madrid', 'Liverpool', 'Manchester City', 'Arsenal'], correctAnswer: 'Real Madrid', category: 'Transferler' },
  { id: 'e8', text: 'Hangi kaleci "Örümcek" (Spider) lakabıyla tanınır?', options: ['Lev Yashin', 'Gianluigi Buffon', 'Petr Cech', 'Manuel Neuer'], correctAnswer: 'Lev Yashin', category: 'Efsaneler' },
  { id: 'e9', text: '2022 Dünya Kupası finalinde Arjantin kalecisi kimdir?', options: ['Emiliano Martinez', 'Franco Armani', 'Geronimo Rulli', 'Nahuel Molina'], correctAnswer: 'Emiliano Martinez', category: 'Dünya Kupası' },
  { id: 'e10', text: 'Hangi futbolcu Şampiyonlar Ligi finalinde iki farklı takımla gol atmıştır?', options: ['Cristiano Ronaldo', 'Mario Mandzukic', 'Robert Lewandowski', 'Hem Ronaldo hem Mandzukic'], correctAnswer: 'Hem Ronaldo hem Mandzukic', category: 'Şampiyonlar Ligi' },
  { id: 'e11', text: 'Süper Lig\'de 100 gol barajını geçen ilk yabancı futbolcu kimdir?', options: ['Alex de Souza', 'Shota Arveladze', 'Elvir Bolic', 'Mert Nobre'], correctAnswer: 'Alex de Souza', category: 'Türkiye' },
  { id: 'e12', text: 'Hangi ülke 1992 Avrupa Şampiyonası\'na son anda davet edilip şampiyon olmuştur?', options: ['Danimarka', 'Yunanistan', 'İsveç', 'Çekoslovakya'], correctAnswer: 'Danimarka', category: 'EURO' },
  { id: 'e13', text: 'Ronaldinho hangi Brezilya kulübünde profesyonel olmuştur?', options: ['Gremio', 'Flamengo', 'Santos', 'Cruzeiro'], correctAnswer: 'Gremio', category: 'Oyuncular' },
  { id: 'e14', text: 'Hangi futbolcu "El Fenomeno" lakabıyla tanınır?', options: ['Ronaldo Nazario', 'Cristiano Ronaldo', 'Ronaldinho', 'Romario'], correctAnswer: 'Ronaldo Nazario', category: 'Efsaneler' },
  { id: 'e15', text: '2016 yılında Premier Lig şampiyonu olan sürpriz takım hangisidir?', options: ['Leicester City', 'Everton', 'West Ham', 'Southampton'], correctAnswer: 'Leicester City', category: 'Ligler' },
  { id: 'e16', text: 'Hangi futbolcu kariyeri boyunca en çok Ballon d\'Or kazanmıştır?', options: ['Lionel Messi', 'Cristiano Ronaldo', 'Michel Platini', 'Johan Cruyff'], correctAnswer: 'Lionel Messi', category: 'Ödüller' },
  { id: 'e17', text: 'Dünya Kupası tarihinde bir maçta en çok gol atan takım hangisidir?', options: ['Macaristan (10 gol)', 'Almanya (8 gol)', 'Yugoslavya (9 gol)', 'Brezilya (7 gol)'], correctAnswer: 'Macaristan (10 gol)', category: 'Dünya Kupası' },
  { id: 'e18', text: 'Hangi teknik direktör 3 farklı takımla Şampiyonlar Ligi kazanmıştır?', options: ['Carlo Ancelotti', 'Pep Guardiola', 'Jose Mourinho', 'Zinedine Zidane'], correctAnswer: 'Carlo Ancelotti', category: 'Teknik Direktörler' },
  { id: 'e19', text: 'Thierry Henry hangi kulübün en golcü oyuncusudur?', options: ['Arsenal', 'Barcelona', 'Monaco', 'Juventus'], correctAnswer: 'Arsenal', category: 'Oyuncular' },
  { id: 'e20', text: 'Hangi ülke 2022 Dünya Kupası\'nda yarı finale çıkan ilk Afrika takımı olmuştur?', options: ['Fas', 'Senegal', 'Kamerun', 'Nijerya'], correctAnswer: 'Fas', category: 'Dünya Kupası' },
];
